<a href="https://colab.research.google.com/github/LeonVillanueva/CoLab/blob/master/Google_CoLab_Simple_RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!pip install -q tensorflow==2.0.0-beta-1

In [0]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [0]:
%%capture

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf

In [0]:
from tensorflow.keras.layers import InputLayer, LSTM, GRU, Input
from tensorflow.keras.models import Model

In [0]:
# always understand the shape

In [0]:
T, D, M = 8, 2, 3 # sequence/time, dimension/factors, nodes

X = np.random.randn(1, T, D)

In [0]:
def my_lstm ():
  input = Input (shape=(T,D)) 
  rnn = LSTM (M, return_state=True)
  x = rnn (input)

  model = Model (inputs=input, outputs=x)
  o, h, c = model.predict(X)

  print ('o: ',o)
  print ('h: ',h)
  print ('c: ',c)

In [0]:
def my_lstm2 ():
  input = Input (shape=(T,D)) 
  rnn = LSTM (M, return_state=True, return_sequences=True)
  x = rnn (input)

  model = Model (inputs=input, outputs=x)
  o, h, c = model.predict(X)

  print ('o: ',o)
  print ('h: ',h)
  print ('c: ',c)

In [0]:
def my_gru ():
  input = Input (shape=(T,D)) 
  rnn = GRU (M, return_state=True)
  x = rnn (input)

  model = Model (inputs=input, outputs=x)
  o, h = model.predict(X)

  print ('o: ',o)
  print ('h: ',h)

In [0]:
def my_gru2 ():
  input = Input (shape=(T,D)) 
  rnn = GRU (M, return_state=True, return_sequences=True)
  x = rnn (input)

  model = Model (inputs=input, outputs=x)
  o, h = model.predict(X)

  print ('o: ',o)
  print ('h: ',h)

In [80]:
my_lstm ()

o:  [[-0.09858694 -0.12637061 -0.21457583]]
h:  [[-0.09858694 -0.12637061 -0.21457583]]
c:  [[-0.21308123 -0.30408397 -0.49650297]]


In [82]:
my_lstm2 ()

o:  [[[-0.1182261   0.13689746 -0.3003321 ]
  [-0.17729257 -0.0577657  -0.01484796]
  [ 0.00560337 -0.10245261  0.13659197]
  [-0.16149825 -0.01220332 -0.12295623]
  [-0.1598244  -0.01566353  0.0044998 ]
  [-0.01283682 -0.09276518  0.14958733]
  [-0.12793627 -0.04178969 -0.02982881]
  [-0.14782223 -0.01416569 -0.02439476]]]
h:  [[-0.14782223 -0.01416569 -0.02439476]]
c:  [[-0.3298971  -0.03018496 -0.04893108]]


In [83]:
my_gru ()

o:  [[ 0.16826515 -0.3128994   0.31435627]]
h:  [[ 0.16826515 -0.3128994   0.31435627]]


In [84]:
my_gru2 ()

o:  [[[-0.07858571  0.01696644  0.81793785]
  [-0.23714423 -0.63776696  0.49423644]
  [-0.31025308 -0.68709165  0.1260936 ]
  [ 0.22029148 -0.49407932  0.5859366 ]
  [-0.0141228  -0.40737993 -0.02373932]
  [-0.10959917 -0.6325676  -0.20704135]
  [ 0.11533076 -0.32929933  0.24530663]
  [-0.05230639 -0.19762248  0.03746351]]]
h:  [[-0.05230639 -0.19762248  0.03746351]]
